import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public class ConcreteStatus2 implements AgentState{
    private final Agent agent;
    final LinkedBlockingQueue<Message> queue;

    public ConcreteStatus2(Agent agent, LinkedBlockingQueue<Message> queue) {
        this.agent = agent;
        this.queue = queue;
    }


    @Override
    public void processing(Context context) throws Exception {
        Message take;
        while (true) {
            take = queue.take();
            if (!take.label.equals(agent.name)) {
                System.out.println(agent.name+"--------------------change to 2----------------------");
                String promptFormat = "You are a generative agent that is capable of comparing the different ontology component explanation in different Knowledge network that is generated by " +
                        "other agents. You are supposed to judge the two ontology are the same thing.Just say yes and no for the judgement and show me the reason.The information is listed below" +
                        ":ontology1:%s,ontology2:%s. The output should be structured like this :Answer:<your answer>,Explanation:<Your Explanation>";
                System.out.println("the agent is aligning");
                String thought = agent.think("http://127.0.0.1:8080/toChatGPT", String.format(promptFormat, agent.list.get(0), take));
                agent.list.add(thought);
                queue.put(new Message(agent.name,thought));
                context.setState(new ConcreteStatus3(this.agent,queue));

                break;
            }else {
                System.out.println("The information will be put back S");
                queue.put(take);
            }
        }
    }
}
